# https://taskfile.dev

version: '3'

vars:
  GOOS: $(go env GOOS)
  GOARCH: $(go env GOARCH)
  VERSION:
    sh: head -n 1 VERSION
  PROJECT: zd
  BUILD_TIME:
    sh: git show -s --format=%cd
  GIT_HASH:
    sh: git show -s --format=%H

tasks:
  gofmt:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  golint:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint run -v ./...

  lint:
    desc: lint code
    cmds:
      - task: gofmt
      - task: golint

  build_ui:
    desc: build ui
    cmds:
      - cd ui && yarn install && yarn build --dest ../client/ui
