title: 产品
desc:
author: zentao
version: 1.0

fields:
  - field: id
    range: 1-10000
    postfix: "\t"

  - field: name
    prefix: "product-"
    range: 1-10000
    postfix: "\t"

  - field: desc
    range: "描述"
