title: 产品
desc:
author: zentao
version: 1.0

fields:
  - field: id
    range: 1-10000

  - field: name
    prefix: "product-"
    range: 100-200
    postfix: "\t"

  - field: desc
#    mode: r
    fields:
      - field: child1
        range: A-C

        prefix: PART1_
        postfix: ' | '

      - field: child2
        range: 0-9

      - field: child3
        range: 0-3,a-z
