title: 测试
desc: 测试文件
author: wwccss
version: 1.0

fields:
  - field: field1
    note: 测试自定义字段
    from: numb.yaml
    use: small,large
    loop: 2

  - field: field2
    note: 测试系统字段
    from: system.ip.v1.yaml
    use: privateC,privateB

  - field: field3
    note: 测试Excel数据
    from: system.address.v1.city
    select: name
    where: state like '%山东%'